batch_size: 500
epochs: 20
labels_for_driven_positive_and_negative_pairs:
wandb_project_name: BIOSCAN-CLIP-5M
using_train_seen_for_pre_train: true
dataset: bioscan_5m

image:
  input_type: image
  pre_train_model: vit_base_patch16_224
dna:
  input_type: sequence
  pre_train_model: barcode_bert

model_output_name: image_dna_text_4gpu-test-run
evaluation_period: 1
ckpt_path: ${project_root_path}/ckpt/bioscan_clip/new_5M_training/trained_with_5M_image_dna/best.pth
output_dim: 768
port: 29531

disable_lora: true
lr_scheduler: one_cycle
lr_config:
  lr: 1e-6
  max_lr: 5e-5

all_gather: true
loss_setup:
  gather_with_grad: true
  use_horovod: false
  local_loss: false
fix_temperature: false
amp: true

random_seed: false

eval_skip_epoch: 10

default_seed: 42

fine_tuning_set:
  batch_size: 150
  epochs: 15
  fine_tune_model_output_dir: ${model_output_dir}/${model_config.model_output_name}/supervise_fine_tune_ckpt